/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      colors: {
        'surface-dim': '#d9d9e0',
        'primary-fixed': '#d6e3ff',
        'on-surface-variant': '#424751',
        'on-background': '#191c20',
        'on-secondary': '#ffffff',
        background: '#f9f9ff',
        'on-surface': '#191c20',
        'on-secondary-container': '#007327',
        'tertiary-fixed-dim': '#ffba20',
        outline: '#737782',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-container-high': '#e7e8ee',
        'on-tertiary-container': '#ebaa00',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#002106',
        'on-primary-fixed-variant': '#00468c',
        tertiary: '#422d00',
        error: '#ba1a1a',
        'surface-container': '#ededf4',
        'tertiary-fixed': '#ffdea8',
        'secondary-container': '#80f98b',
        'surface-container-highest': '#e2e2e9',
        'on-primary-container': '#8cb6ff',
        'primary-fixed-dim': '#a9c7ff',
        'surface-container-low': '#f3f3fa',
        'surface-bright': '#f9f9ff',
        'on-tertiary-fixed-variant': '#5e4200',
        'on-primary': '#ffffff',
        'secondary-fixed': '#83fc8e',
        'on-tertiary-fixed': '#271900',
        'outline-variant': '#c2c6d2',
        'tertiary-container': '#5e4200',
        'secondary-fixed-dim': '#66df75',
        'surface-variant': '#e2e2e9',
        'on-primary-fixed': '#001b3d',
        'inverse-primary': '#a9c7ff',
        surface: '#f9f9ff',
        secondary: '#006e25',
        'primary-container': '#00468c',
        primary: '#003063',
        'inverse-surface': '#2e3035',
        'surface-tint': '#2a5ea5',
        'on-secondary-fixed-variant': '#00531a',
        'inverse-on-surface': '#f0f0f7',
        'on-tertiary': '#ffffff',
      },
    },
  },
  plugins: [],
}


